
import { GoogleGenAI } from "@google/genai";

/**
 * Transforms a sketch (base64) and prompt into a high-quality image.
 */
export const generateImageFromSketch = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  // Extract data part of base64 string
  const base64Data = base64Image.split(',')[1];

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/png',
            },
          },
          {
            text: `High resolution, professional artwork based on this sketch. ${prompt}. Maintain the composition and main shapes of the sketch but render it with realistic or artistic detail.`,
          },
        ],
      },
    });

    let imageUrl = '';
    // The response can contain multiple parts, iterate to find the image part
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
